### ISSUE TITLE
TODO/FIXME Count 5

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-account#16]
- [ ] TODO: deprecate auto-retrieving capabilities, require devs to call
       Commit: (a360337) Add TODO.
       File:  [lib/index.js:714](https://github.com/digitalbazaar/bedrock-account/blob/master/lib/index.js#L714)
       Dave Longley commented 2 years ago

  - [ ] FIXME: call update meta on brIdentity or update sequence here
       Commit: (ae1eebd) Ensure `sequence` is updated.
       File:  [lib/index.js:625](https://github.com/digitalbazaar/bedrock-account/blob/master/lib/index.js#L625)
       Dave Longley commented 2 years ago

  - [ ] TODO: deprecate use of `id` here?
       Commit: (b1f032e) Add TODO.
       File:  [lib/index.js:550](https://github.com/digitalbazaar/bedrock-account/blob/master/lib/index.js#L550)
       Dave Longley commented 2 years ago

  - [ ] FIXME remove options.fields from all libraries that call on bedrock-account
       Commit: (183d870) Allow fields to be undefined.
       File:  [lib/index.js:298](https://github.com/digitalbazaar/bedrock-account/blob/master/lib/index.js#L298)
       Andrew L Jones commented 13 days ago

  - [ ] TODO: move permission check to after query to allow users with
       Commit: (16e72ca) Add core API.
       File:  [lib/index.js:288](https://github.com/digitalbazaar/bedrock-account/blob/master/lib/index.js#L288)
       Dave Longley commented 2 years ago

**Comment by dlongley** [comment]
All TODOs/FIXMEs addressed / removed.
